version: 2

before:
  hooks:
    - buf generate

builds:
  - id: ores
    main: ./cmd/ores
    binary: ores
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w

  - id: oresd
    main: ./cmd/oresd
    binary: oresd
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w

  - id: ores-wasm
    main: ./pkg/wasm
    binary: ores
    goos: [wasip1]
    goarch: [wasm]
    ldflags:
      - -s -w

kos:
  - id: oresd
    main: ./cmd/oresd
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - latest
      - "{{.Version}}"
    sbom: spdx

archives:
  - id: ores
    builds: [ores]
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

  - id: oresd
    builds: [oresd]
    format: tar.gz

  - id: wasm
    builds: [ores-wasm]
    format: tar.gz
    name_template: "ores-wasm_{{ .Version }}"

checksum:
  name_template: checksums.txt

signs:
  - cmd: cosign
    args: ["sign-blob", "--yes", "--output-signature=${signature}", "${artifact}"]
    artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore"
      - "^docs"
      - "^test"
